- service_name: 'com.amazonaws.eu-west-1.ecr.api'
  vpc_id: '<VPC_ID>'
  name: 'ecr-api-endpoint'
  type: 'Interface'
  subnet_ids:
    - '<SUBNET_ID>'
  security_group_ids:
    - '<SECURITY_GROUP>'
  resource_type: 'vpc-endpoint'
  private_dns: True
  dns:
    dns_record_ip_type: 'ipv4'
- service_name: 'com.amazonaws.eu-west-1.ecr.dkr'
  vpc_id: '<VPC_ID>'
  name: 'ecr-dkr-endpoint'
  type: 'Interface'
  subnet_ids:
    - '<SUBNET_ID>'
  security_group_ids:
    - '<SECURITY_GROUP>'
  resource_type: 'vpc-endpoint'
  private_dns: True
  dns:
    dns_record_ip_type: 'ipv4'
- service_name: 'com.amazonaws.eu-west-1.logs'
  vpc_id: '<VPC_ID>'
  name: 'cloudwatch-endpoint'
  type: 'Interface'
  subnet_ids:
    - '<SUBNET_ID>'
  security_group_ids:
    - '<SECURITY_GROUP>'
  resource_type: 'vpc-endpoint'
  private_dns: True
  dns:
    dns_record_ip_type: 'ipv4'
- service_name: 'com.amazonaws.eu-west-1.s3'
  vpc_id: '<VPC_ID>'
  name: 's3-gateway'
  type: 'Gateway'
  resource_type: 'vpc-endpoint'
  route_table_ids:
    - '<ROUTE_TABLE_ID>'